# Generate builtins/transcode_tables.h from CRuby's own encoding data.
#
#   ruby tools/gen_transcode.rb > builtins/transcode_tables.h
#
# Single-byte encodings become a 128-entry uint16 table (0x80..0xFF -> codepoint,
# 0xFFFF = undefined).  Multi-byte legacy encodings become two sorted arrays
# (byte-sequence -> codepoint and codepoint -> byte-sequence) so both directions
# are a binary search.  The ASCII range is never tabulated: every encoding here
# is ASCII-transparent below 0x80.

SINGLE = %w[
  ISO-8859-1 ISO-8859-2 ISO-8859-3 ISO-8859-4 ISO-8859-5 ISO-8859-6 ISO-8859-7
  ISO-8859-8 ISO-8859-9 ISO-8859-10 ISO-8859-11 ISO-8859-13 ISO-8859-14
  ISO-8859-15 ISO-8859-16
  Windows-1250 Windows-1251 Windows-1252 Windows-1253 Windows-1254 Windows-1255
  Windows-1256 Windows-1257 Windows-1258 Windows-874
  KOI8-R KOI8-U TIS-620 GB1988
  IBM437 IBM720 IBM737 IBM775 IBM852 IBM855 IBM857 IBM860 IBM861 IBM862 IBM863
  IBM864 IBM865 IBM866 IBM869 CP850 CP852 CP855
  macRoman macCentEuro macCroatian macCyrillic macGreek macIceland macRomania
  macThai macTurkish macUkraine
]

# Kept deliberately small: these four cover the Japanese legacy encodings the
# specs and real code actually use.  Adding Big5/GBK/EUC-KR would triple the
# table size for encodings nothing here exercises.
MULTI = %w[Shift_JIS Windows-31J EUC-JP CP51932]

def cname(n) = n.gsub(/[^A-Za-z0-9]/, "_").upcase

def single_table(name)
  enc = Encoding.find(name)
  (0x80..0xFF).map do |b|
    s = b.chr(enc)
    if s.valid_encoding? && s.length == 1
      begin
        s.encode(Encoding::UTF_8).ord
      rescue StandardError
        0xFFFF
      end
    else
      0xFFFF
    end
  end
end

# Enumerate every codepoint that `enc` can represent, by asking CRuby to encode
# each Unicode scalar.  Slow but exact, and it runs once.
def multi_pairs(name)
  enc = Encoding.find(name)
  pairs = []
  ranges = [0x80..0xD7FF, 0xE000..0xFFFD, 0x10000..0x10FFFF]
  ranges.each do |r|
    r.each do |cp|
      s = begin
        [cp].pack("U")
      rescue StandardError
        next
      end
      b = begin
        s.encode(enc)
      rescue StandardError
        next
      end
      bytes = b.bytes
      next if bytes.size > 4
      v = 0
      bytes.each { |x| v = (v << 8) | x }
      pairs << [v, bytes.size, cp]
    end
  end
  pairs
end

puts "/* Generated by tools/gen_transcode.rb — do not edit. */"
puts "/* Source: CRuby #{RUBY_VERSION} encoding tables. */"
puts "#ifndef KORB_TRANSCODE_TABLES_H"
puts "#define KORB_TRANSCODE_TABLES_H 1"
puts

single_ok = []
SINGLE.each do |name|
  next unless Encoding.name_list.include?(name) || (Encoding.find(name) rescue nil)
  t = single_table(name)
  single_ok << name
  puts "static const uint16_t korb_sb_#{cname(name)}[128] = {"
  t.each_slice(8) { |row| puts "    " + row.map { |v| format("0x%04X", v) }.join(", ") + "," }
  puts "};"
end
puts

multi_ok = []
MULTI.each do |name|
  next unless (Encoding.find(name) rescue nil)
  pairs = multi_pairs(name)
  next if pairs.empty?
  multi_ok << [name, pairs.size]
  by_bytes = pairs.sort_by { |v, _n, _cp| v }
  by_cp    = pairs.sort_by { |_v, _n, cp| cp }
  puts "/* #{name}: #{pairs.size} mappings */"
  puts "static const struct korb_tc_pair korb_mb_#{cname(name)}_b[#{pairs.size}] = {"
  by_bytes.each_slice(6) do |row|
    puts "    " + row.map { |v, n, cp| format("{0x%06X,%d,0x%05X}", v, n, cp) }.join(",") + ","
  end
  puts "};"
  puts "static const struct korb_tc_pair korb_mb_#{cname(name)}_c[#{pairs.size}] = {"
  by_cp.each_slice(6) do |row|
    puts "    " + row.map { |v, n, cp| format("{0x%06X,%d,0x%05X}", v, n, cp) }.join(",") + ","
  end
  puts "};"
end
puts

puts "static const struct korb_tc_sb_ent korb_tc_sb_table[] = {"
single_ok.each { |name| puts %(    { "#{name}", korb_sb_#{cname(name)} },) }
puts "    { NULL, NULL },"
puts "};"
puts "static const struct korb_tc_mb_ent korb_tc_mb_table[] = {"
multi_ok.each do |name, n|
  puts %(    { "#{name}", korb_mb_#{cname(name)}_b, korb_mb_#{cname(name)}_c, #{n} },)
end
puts "    { NULL, NULL, NULL, 0 },"
puts "};"
puts
puts "#endif /* KORB_TRANSCODE_TABLES_H */"
