# Emit builtins/unicode_case.h from the host Ruby's own case mapping.
#
# The tables are exactly what `String#upcase` / `#downcase` / `#downcase(:fold)`
# do for a single character, so koruby matches CRuby by construction rather than
# by re-deriving UnicodeData.txt.  Run after a Unicode version bump:
#   ruby tools/gen_unicode_case.rb > builtins/unicode_case.h

MAX = 0x2FFFF        # everything above this plane is caseless

up = []; down = []; up_multi = []; down_multi = []; fold_multi = []

(0..MAX).each do |cp|
  next if (0xD800..0xDFFF).cover?(cp)
  ch = begin
    cp.chr(Encoding::UTF_8)
  rescue RangeError
    next
  end
  u = ch.upcase
  d = ch.downcase
  f = ch.downcase(:fold)
  if u != ch
    u.length == 1 ? up << [cp, u.ord] : up_multi << [cp, u]
  end
  if d != ch
    d.length == 1 ? down << [cp, d.ord] : down_multi << [cp, d]
  end
  fold_multi << [cp, f] if f != d
end

def cstr(s)
  '"' + s.bytes.map { |b| format('\\x%02x', b) }.join + '"'
end

puts <<~HEAD
  /* Generated by tools/gen_unicode_case.rb from Ruby #{RUBY_VERSION}
   * (Unicode #{RbConfig::CONFIG['UNICODE_VERSION'] || '?'}).  Do not edit. */
  struct korb_case_pair { uint32_t from, to; };
  struct korb_case_multi { uint32_t from; const char *to; };
HEAD

[['korb_case_up', up], ['korb_case_down', down]].each do |name, tbl|
  puts "static const struct korb_case_pair #{name}[] = {"
  tbl.sort_by!(&:first)
  tbl.each_slice(6) do |row|
    puts '    ' + row.map { |a, b| format('{0x%04X,0x%04X},', a, b) }.join(' ')
  end
  puts "};"
  puts "#define #{name.upcase}_N (sizeof #{name} / sizeof #{name}[0])"
end

[['korb_case_up_multi', up_multi], ['korb_case_down_multi', down_multi],
 ['korb_case_fold_multi', fold_multi]].each do |name, tbl|
  puts "static const struct korb_case_multi #{name}[] = {"
  tbl.sort_by!(&:first)
  tbl.each { |cp, s| puts format('    {0x%04X, %s},', cp, cstr(s)) }
  puts "};"
  puts "#define #{name.upcase}_N (sizeof #{name} / sizeof #{name}[0])"
end
