#!/usr/bin/env ruby
# Emit a C TU embedding the concatenated prelude source (wasm interpreter:
# no filesystem mount needed at startup).  The file list and its order are
# read from main.c's KORUBY_PRELUDE_FILES so there is a single source of
# truth; the concatenation (one "\n" appended per file) must match
# load_prelude_source in main.c.
#
# usage: ruby tools/gen_prelude_blob.rb <sample_dir> > prelude_blob.c

dir = ARGV[0] or abort "usage: gen_prelude_blob.rb <sample_dir>"
main = File.read(File.join(dir, "main.c"))
list = main[/KORUBY_PRELUDE_FILES\[\]\s*=\s*\{(.*?)\};/m, 1] or
  abort "gen_prelude_blob: KORUBY_PRELUDE_FILES not found in main.c"
files = list.scan(/"([^"]+)"/).flatten
abort "gen_prelude_blob: empty file list" if files.empty?

blob = +""
files.each { |f| blob << File.binread(File.join(dir, "prelude", f)) << "\n" }

puts "/* Auto-generated by tools/gen_prelude_blob.rb — concatenated prelude"
puts " * (#{files.size} files, #{blob.bytesize} bytes).  Do not edit. */"
puts "#include <stddef.h>"
print "const char koruby_prelude_blob[] = {"
blob.each_byte.each_slice(16).with_index do |bytes, i|
  print "\n  "
  print bytes.map { |b| "%d," % b }.join
end
puts "\n};"
puts "const size_t koruby_prelude_blob_len = #{blob.bytesize};"
