// luastro — Lua 5.4 interpreter on the ASTro framework.
//
// Front-end:    lua_tokenizer.c, lua_parser.c
// Runtime:      lua_runtime.c, lua_stdlib.c
// Generated:    node_eval.c, node_dispatch.c, ... (from node.def)
// Glue / main:  this file plus node.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <malloc.h>
#include <sys/resource.h>
#include "context.h"
#include "node.h"
#include "astro_code_store.h"

#include <pthread.h>

// Run the program body on a worker thread with a much larger C stack
// than the default 8 MB.  The SD inline-closure-call chain grows the C
// stack one frame per Lua function invocation, and SD frames can be
// ~500 bytes each for non-trivial functions — deeply recursive programs
// like ack(3, 8) blow through 8 MB easily.  64 MB is plenty for the
// programs we care about and is well below typical address-space
// limits.
typedef struct { int (*entry)(void *); void *arg; int rc; } luastro_thread_arg;
static void *luastro_thread_main(void *p) {
    luastro_thread_arg *a = (luastro_thread_arg *)p;
    a->rc = a->entry(a->arg);
    return NULL;
}
struct run_args { CTX *c; struct ParsedChunk *pc; };
static LuaValue run_chunk(CTX *c, struct ParsedChunk *pc);

static int
luastro_run_chunk_thunk(void *p)
{
    struct run_args *a = (struct run_args *)p;
    (void)run_chunk(a->c, a->pc);
    return 0;
}

static int
luastro_run_on_big_stack(int (*entry)(void *), void *arg)
{
    pthread_attr_t at; pthread_attr_init(&at);
    pthread_attr_setstacksize(&at, 4ULL * 1024 * 1024 * 1024);  // 4 GB virtual
    luastro_thread_arg ta = { entry, arg, 0 };
    pthread_t tid;
    if (pthread_create(&tid, &at, luastro_thread_main, &ta) != 0) {
        pthread_attr_destroy(&at);
        return entry(arg);   // fall back: run on main stack
    }
    pthread_attr_destroy(&at);
    pthread_join(tid, NULL);
    return ta.rc;
}

struct luastro_option OPTION = {0};

// Forward decls (front-end / stdlib / runtime).
struct ParsedChunk { NODE *body; uint32_t nlocals, nupvals, nparams; bool is_vararg; };
NODE *PARSE_lua(const char *src, const char *filename, struct ParsedChunk *out);
void  luastro_init_globals(CTX *c);
void  luastro_specialize_all(NODE *root, const char *file);
void  code_repo_add(const char *name, NODE *body, bool force);

#include "lua_tokenizer.c"
#include "lua_parser.c"
#include "lua_runtime.c"
#include "lua_stdlib.c"

// --- Read whole file ---

static char *
read_file(const char *path)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "luastro: cannot open '%s': %s\n", path, strerror(errno));
        exit(1);
    }
    fseek(fp, 0, SEEK_END);
    long sz = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    char *buf = (char *)malloc(sz + 1);
    if (fread(buf, 1, sz, fp) != (size_t)sz) {
        fprintf(stderr, "luastro: read error\n");
        exit(1);
    }
    buf[sz] = '\0';
    fclose(fp);
    return buf;
}

// --- Run a parsed chunk as a closure with no upvalues ---

static LuaValue
run_chunk(CTX *c, struct ParsedChunk *pc)
{
    struct LuaClosure *cl = lua_closure_new(pc->body, pc->nparams,
                                            pc->nlocals, pc->nupvals,
                                            pc->is_vararg, "<chunk>");
    LuaValue r = lua_call(c, LUAV_FUNC(cl), NULL, 0);
    return r;
}

// --- Generate node_specialized.c (mirrors naruby's --pg-compile output) ---
//
// `file` selects bake mode:
//   - NULL: AOT (SD_<HORG>).  Used by `-c` and `--aot-compile`.
//   - non-NULL: PGC (PGSD_<HOPT>) keyed by (HORG, file, line) → HOPT in
//     hopt_index.txt.  Used by `-p` after a profile run has fired
//     swap_dispatcher across observed type-specialised nodes.

static void
generate_specialized_code(NODE *root, const char *file)
{
    luastro_specialize_all(root, file);

    // Snapshot to local file for the AOT/PG bake step (compiled_luastro
    // and pg_luastro) to embed.
    FILE *fp = fopen("node_specialized.c", "w");
    if (!fp) { perror("node_specialized.c"); return; }
    fprintf(fp,
        "// Auto-generated by luastro --pg-compile / -c.\n"
        "// Empty: PGC bake collected via code_store/ at runtime.\n");
    fclose(fp);
}

static void
usage(void)
{
    fprintf(stderr,
        "usage: luastro [options] <file.lua> [args...]\n"
        "options:\n"
        "  -e <chunk>           run literal chunk\n"
        "  -c, --aot-compile-first\n"
        "                       AOT-bake SDs into code_store/, then run with them active\n"
        "  --aot-compile        AOT-bake SDs into code_store/ and exit (no run)\n"
        "  -p, --pg-compile     run first (profile), then bake SDs\n"
        "  --no-compile         don't consult / write code store (pure interpreter)\n"
        "  --dump-ast           print AST\n"
        "  -q                   quiet\n"
        "  -v                   verbose\n"
        "  -h, --help           this help\n");
    exit(2);
}

int
main(int argc, char *argv[])
{
    // Force a single glibc malloc arena so the worker thread spawned
    // by `luastro_run_on_big_stack` doesn't get its own per-thread
    // arena.  Per-thread arenas are mmap'd lazily and committed in
    // 4 KiB chunks via `mprotect(PROT_READ|PROT_WRITE)` — on bm_storage
    // (which mallocs ~1 M tables) that came out as 58k mprotect calls
    // worth ~170 ms of pure kernel overhead per process.  Single-arena
    // routes the thread's allocations through `brk` like the main
    // thread, dropping the mprotect count to zero.  See bench delta on
    // storage: 0.42 s → 0.30 s after this single line.
    mallopt(M_ARENA_MAX, 1);

    const char *file = NULL;
    const char *eval_str = NULL;

    int ai = 1;
    while (ai < argc && argv[ai][0] == '-' && argv[ai][1] != '\0') {
        const char *a = argv[ai++];
        if      (!strcmp(a, "-q"))                       OPTION.quiet = true;
        else if (!strcmp(a, "-v"))                       OPTION.verbose = true;
        else if (!strcmp(a, "--no-compile"))             OPTION.no_compiled_code = true;
        else if (!strcmp(a, "-c") ||
                 !strcmp(a, "--aot-compile-first"))      OPTION.compile_first = true;
        else if (!strcmp(a, "--aot-compile"))            OPTION.aot_only = true;
        else if (!strcmp(a, "-p") ||
                 !strcmp(a, "--pg-compile"))             OPTION.pg_mode = true;
        else if (!strcmp(a, "--dump-ast"))               OPTION.dump_ast = true;
        else if (!strcmp(a, "-e")) {
            if (ai >= argc) usage();
            eval_str = argv[ai++];
        }
        else if (!strcmp(a, "-h") || !strcmp(a, "--help")) usage();
        else if (!strcmp(a, "--")) break;
        else { fprintf(stderr, "luastro: unknown option %s\n", a); usage(); }
    }
    if (!eval_str) {
        if (ai >= argc) usage();
        file = argv[ai++];
    }

    INIT();
    CTX *c = luastro_create_context();
    luastro_init_globals(c);

    char *src = NULL;
    const char *src_name = "=stdin";
    if (eval_str) { src = strdup(eval_str); src_name = "=(command line)"; }
    else          { src = read_file(file);  src_name = file; }

    // Make the source filename available to OPTIMIZE (called from each
    // ALLOC_*) so PGC lookup can compute (HORG, file, line) → HOPT.
    extern const char *luastro_current_src_file;
    luastro_current_src_file = src_name;

    struct ParsedChunk pc;
    NODE *body = PARSE_lua(src, src_name, &pc);

    if (OPTION.dump_ast) { DUMP(stdout, body, false); printf("\n"); }

    // Modes:
    //   default              — interpret with whatever code-store SDs are loaded
    //   -c / --aot-compile-first — bake SDs first (AOT), then run
    //   --aot-compile        — bake AOT and exit (used by benchmark setup)
    //   -p / --pg-compile    — run first (collect profile via swap_dispatcher),
    //                          then bake PGC SDs keyed off the post-swap kinds
    if (OPTION.compile_first || OPTION.aot_only) {
        generate_specialized_code(body, NULL);
        if (OPTION.aot_only) { free(src); return 0; }
    }
    {
        OPTIMIZE(body);
        extern void luastro_optimize_stats(void);
        luastro_optimize_stats();
        // Run the chunk on a worker thread with a much larger C stack
        // than the default 8 MB so deep recursive programs don't blow
        // through the kernel guard page (SD frames are ~1 KB).
        struct run_args ra = { c, &pc };
        luastro_run_on_big_stack(luastro_run_chunk_thunk, &ra);
    }
    if (OPTION.pg_mode) {
        // Backoff: if no node observed a profile-driven swap_dispatcher,
        // PGC bake degenerates to "SD with extra hopt_index probe per
        // cs_load".  Use AOT bake (file=NULL) instead so cached load
        // dlsym's SD_<HORG> directly without the index detour.
        extern bool luastro_any_kind_swapped(void);
        const char *bake_file = luastro_any_kind_swapped() ? src_name : NULL;
        generate_specialized_code(body, bake_file);
    }
    free(src);
    return 0;
}
