// ASTro framework public API.
//
// Declared here for use by language exe drivers and build helpers that
// don't #include the language's node.c (where astro_node.c is included).
//
// `struct Node` is forward-declared so this header is independent of
// node.h ordering; callers that need to actually deref nodes must
// include the language's node.h.

#ifndef ASTRO_NODE_H
#define ASTRO_NODE_H

#include <stdio.h>

struct Node;

// ---------------------------------------------------------------------------
// AST → C source emitters (defined in astro_node.c, exposed by node.c).
// Used by --generate-executable to embed a parsed AST in a generated exe.
// ---------------------------------------------------------------------------

// Walk `n` and write the textual `ALLOC_<kind>(...)` expression to fp.
// Recursive: child NODEs are emitted in-place.
void astro_emit_ast_c(FILE *fp, struct Node *n);

// Used by EMIT_AST_<kind> helpers (auto-generated by ASTroGen) when
// emitting a NODE * operand.  The behaviour depends on the active
// emission mode:
//   - Recursive (calc-style):  recurses into astro_emit_ast_c.
//   - Flat / DAG (naruby-style): emits `_n[id]` referencing a slot in
//     the static array built by astro_emit_ast_c_program.
void astro_emit_ast_c_child(FILE *fp, struct Node *child);

// Mode 1: simple recursive emission.  Use for samples without node
// sharing or cycles.  Output is a single expression with sub-trees
// inlined.
void astro_emit_ast_c_file(FILE *fp, struct Node *root,
                           const char *func_name,
                           const char *include_header);

// Mode 2: DAG-aware flat emission.  Assigns each unique NODE a
// sequential ID via DFS post-order, then emits one ALLOC line per
// node referencing children via `_n[id]`.  Cycle back-edges are
// resolved separately by the host (via callsite_resolve or similar).
void astro_emit_ast_c_program(FILE *fp, struct Node *root,
                              const char *func_name,
                              const char *include_header);

// Same, but the generated function takes `params` (e.g. "CTX *_ectx") instead
// of void — for hosts whose operand emitters need runtime context (interning
// symbol names at exe startup).  NULL params = "void".
void astro_emit_ast_c_program_params(FILE *fp, struct Node *root,
                                     const char *func_name,
                                     const char *include_header,
                                     const char *params);

#endif // ASTRO_NODE_H
