#!/usr/bin/env ruby
# Matrix runner (iter 35) — rebuilds the binary per backend, verifies that
# `__GC_STATS__ backend=` matches the requested backend (no Makefile-stale
# binary like iter 31), checksums the result against a known oracle, and
# emits CSV + Markdown + JSON.
#
# Usage:
#   ruby bench/matrix.rb [--mode plain|aot|pg] [--repeats N] [--choose best|median|trimmed]
#                       [--backends a,b,c] [--benches x,y,z]
#                       [--out-dir <path>]
#
# The default backend list excludes copy_gen_inc (currently a placeholder
# — see gc_copy_gen_inc.c iter 35 honesty note).

require 'optparse'
require 'fileutils'
require 'digest'
require 'json'

ROOT = File.expand_path("../..", __FILE__)
BENCH_DIR = File.expand_path("..", __FILE__)
ALL_BACKENDS = %w(none mark mark_gen mark_gen_inc copy copy_gen
                  mark_compact mark_compact_gen bump mark_bump_gen
                  immix immix_gen mark_bitmap_gen)
# copy_gen_inc excluded — see gc_copy_gen_inc.c

# Sister sample: libgc (Boehm conservative).  Treated as an additional
# column when --include-libgc is set (or default if its binary exists).
LIBGC_BIN_DEFAULT = File.expand_path("../../baruby/baruby", BENCH_DIR)
# life.ba.rb has a known top-level-return-value bug on the libgc side
# (separate from GC — independent main.c issue).  Skip it for libgc only.
LIBGC_SKIP_BENCHES = %w(life)

opts = {
  mode: "plain",
  repeats: 3,
  choose: "median",
  backends: ALL_BACKENDS,
  benches: Dir["#{BENCH_DIR}/*.ba.rb"].map { |p| File.basename(p, ".ba.rb") }.sort,
  out_dir: File.join(ROOT, "bench-results"),
  astro_debug: 0,
  libgc_bin: File.exist?(LIBGC_BIN_DEFAULT) ? LIBGC_BIN_DEFAULT : nil,
}
OptionParser.new do |o|
  o.on("--mode MODE")        { opts[:mode] = _1 }
  o.on("-n N", "--repeats N", Integer) { opts[:repeats] = _1 }
  o.on("--choose POL")       { opts[:choose] = _1 }
  o.on("--backends LIST")    { opts[:backends] = _1.split(",") }
  o.on("--benches LIST")     { opts[:benches] = _1.split(",") }
  o.on("--out-dir DIR")      { opts[:out_dir] = _1 }
  o.on("--astro-debug N", Integer) { opts[:astro_debug] = _1 }
  o.on("--libgc-bin PATH")   { opts[:libgc_bin] = _1 }
  o.on("--no-libgc")         { opts[:libgc_bin] = nil }
end.parse!(ARGV)

FileUtils.mkdir_p(opts[:out_dir])

flag = case opts[:mode]
       when "plain" then ["--plain"]
       when "aot"   then ["-c"]
       when "pg"    then ["-p"]
       else abort "unknown mode #{opts[:mode]}"
       end

# AOT bakes invoke `cc` via make.  If the host has ccache aliased as cc,
# its temp-file path can collide with our sandbox restrictions.  Force
# CCACHE_DISABLE=1 for the duration of the bake so the bake's gcc runs
# directly.  (Documented quirk — see CLAUDE.md / memory.)
ENV["CCACHE_DISABLE"] = "1" if opts[:mode] == "aot" || opts[:mode] == "pg"

# Known-good result oracle.  Generated by running each bench under `mark`
# (well-tested non-moving) and freezing the checksum.  Updated only when
# bench source changes.
ORACLE_FILE = File.join(BENCH_DIR, "oracle.json")
ORACLE = File.exist?(ORACLE_FILE) ? JSON.parse(File.read(ORACLE_FILE)) : {}

def build(gc, astro_debug)
  system("cd #{ROOT} && make GC=#{gc} ASTRO_DEBUG=#{astro_debug}",
         out: "/tmp/matrix_build_#{gc}.log", err: [:child, :out])
end

def parse_run(out)
  elapsed = out[/__ELAPSED__\s+(\S+)/, 1]&.to_f
  return nil unless elapsed
  result = out[/^Result:\s*([\d.-]+)/, 1]
  h = { elapsed: elapsed, result: result }
  if (line = out[/^__GC_STATS__\s+(.*)$/, 1])
    line.split(/\s+/).each do |kv|
      k, v = kv.split('=', 2)
      h[k.to_sym] = v if k && v
    end
  end
  h
end

def pick(runs, policy)
  return nil if runs.empty?
  by_time = runs.sort_by { |r| r[:elapsed] }
  case policy
  when "best"    then by_time.first
  when "median"  then by_time[runs.size / 2]
  when "trimmed"
    return by_time[runs.size / 2] if runs.size < 4
    by_time[1..-2][by_time[1..-2].size / 2]
  else by_time[runs.size / 2]
  end
end

# Per-cell result: { elapsed, result, gc_stats, all_runs }
matrix = {}     # matrix[bench][backend] = chosen_run_hash

# Final list of "backends" for output includes the optional libgc column.
column_order = opts[:backends].dup
column_order << "libgc" if opts[:libgc_bin]

# Run libgc first (no rebuild needed).  Skipping after build loop would have
# us pay one rebuild cost just to NOT use the binary.
if opts[:libgc_bin]
  unless File.exist?(opts[:libgc_bin])
    abort "libgc bin not found: #{opts[:libgc_bin]} (use --no-libgc to skip)"
  end
  puts "=== libgc binary: #{opts[:libgc_bin]} (no rebuild) ==="
  opts[:benches].each do |bench|
    next if LIBGC_SKIP_BENCHES.include?(bench)
    bench_path = File.join(BENCH_DIR, "#{bench}.ba.rb")
    next unless File.exist?(bench_path)
    runs = []
    opts[:repeats].times do
      cmd = [opts[:libgc_bin], *flag, bench_path]
      out = IO.popen(cmd, err: [:child, :out]) { |io| io.read }
      h = parse_run(out)
      if h
        if ORACLE[bench] && h[:result] && h[:result] != ORACLE[bench]
          warn "  ⚠ libgc/#{bench}: result mismatch (got #{h[:result]}, oracle #{ORACLE[bench]}) — continuing"
        end
        runs << h
      end
    end
    chosen = pick(runs, opts[:choose])
    matrix[bench] ||= {}
    matrix[bench]["libgc"] = chosen
    printf "  %-20s %-25s %s\n", "libgc", bench, chosen ? "#{chosen[:elapsed]}s" : "FAIL"
  end
end

opts[:backends].each do |gc|
  print "=== Build GC=#{gc} (ASTRO_DEBUG=#{opts[:astro_debug]}) "
  if !build(gc, opts[:astro_debug])
    puts "FAILED"
    next
  end
  puts "OK"

  bin = File.join(ROOT, "baruby_precise")
  # Verify the binary's backend stamp via `strings`.  If it doesn't match
  # we know the Makefile bug from iter 32 has resurfaced.
  stamp = `strings #{bin} | grep -oE 'baruby_gc=[a-z_]+' | sort -u | head -1`.strip
  expected = "baruby_gc=#{gc}"
  unless stamp.include?("baruby_gc=#{gc}") || stamp.empty?
    # `bump` / `none` don't emit `baruby_gc=`; skip the warning for them
    warn "  ⚠ stamp mismatch: expected #{expected}, got #{stamp.inspect}"
  end

  opts[:benches].each do |bench|
    bench_path = File.join(BENCH_DIR, "#{bench}.ba.rb")
    next unless File.exist?(bench_path)
    # AOT/PG mode: clear code_store between benches so each (backend, bench)
    # pair gets a fresh bake.  Without this, SDs from earlier benches in the
    # same backend's loop pollute the cache and partial-AOT timings result
    # (observed iter 36: fib_pair after fannkuch went 0.5 → 1.05s).
    if opts[:mode] == "aot" || opts[:mode] == "pg"
      FileUtils.rm_rf(File.join(ROOT, "code_store"))
    end
    runs = []
    opts[:repeats].times do
      env = { "BARUBY_GC_STATS" => "1" }
      cmd = [env, bin, *flag, bench_path]
      out = IO.popen(cmd, err: [:child, :out]) { |io| io.read }
      h = parse_run(out)
      if h
        # Verify GC_STATS backend matches what we built
        actual_bk = h[:backend]
        if actual_bk && actual_bk != gc
          abort "FATAL: backend mismatch — expected #{gc}, got #{actual_bk}"
        end
        # Verify result checksum if oracle known
        if ORACLE[bench] && h[:result] != ORACLE[bench]
          abort "FATAL: result mismatch on #{gc}/#{bench}: expected #{ORACLE[bench]}, got #{h[:result]}"
        end
        runs << h
      end
    end
    chosen = pick(runs, opts[:choose])
    matrix[bench] ||= {}
    matrix[bench][gc] = chosen
    printf "  %-20s %-25s %s\n", gc, bench, chosen ? "#{chosen[:elapsed]}s" : "FAIL"
  end
end

# ---------- Emit CSV ----------
csv_path = File.join(opts[:out_dir], "matrix.csv")
File.open(csv_path, "w") do |f|
  cols = %w(bench backend elapsed gc_count minor major gc_seconds mark_seconds reclaim_seconds gc_pct max_pause_ms alloc_bytes result)
  f.puts cols.join(",")
  matrix.each do |bench, by_bk|
    by_bk.each do |bk, r|
      next unless r
      vals = [bench, bk,
              r[:elapsed],
              r[:gc_count] || "",
              r[:minor] || "",
              r[:major] || "",
              r[:gc_seconds] || "",
              r[:mark_seconds] || "",
              r[:reclaim_seconds] || "",
              r[:gc_pct] || "",
              r[:max_pause_ms] || "",
              r[:alloc_bytes] || "",
              r[:result] || ""]
      f.puts vals.map { |v| v.to_s.include?(",") ? v.inspect : v.to_s }.join(",")
    end
  end
end
puts "wrote #{csv_path}"

# ---------- Emit JSON ----------
json_path = File.join(opts[:out_dir], "matrix.json")
File.write(json_path, JSON.pretty_generate({
  meta: {
    mode: opts[:mode], repeats: opts[:repeats], choose: opts[:choose],
    astro_debug: opts[:astro_debug], backends: opts[:backends],
    benches: opts[:benches], generated_at: Time.now.utc.iso8601,
  },
  matrix: matrix,
}))
puts "wrote #{json_path}"

# ---------- Emit Markdown ----------
md_path = File.join(opts[:out_dir], "matrix.md")
File.open(md_path, "w") do |f|
  f.puts "# baruby_precise — backend matrix (#{opts[:choose]} of #{opts[:repeats]} runs)"
  f.puts ""
  f.puts "Build: `make GC=<backend> ASTRO_DEBUG=#{opts[:astro_debug]}`, mode `#{opts[:mode]}`."
  f.puts "Generated: #{Time.now.utc.iso8601}"
  f.puts ""
  f.puts "| Bench | " + column_order.join(" | ") + " |"
  f.puts "|---" + ("|---:" * column_order.size) + "|"
  matrix.keys.sort.each do |bench|
    row_vals = column_order.map { |bk| matrix[bench][bk]&.dig(:elapsed) }
    best     = row_vals.compact.min
    cells = column_order.map do |bk|
      v = matrix[bench][bk]&.dig(:elapsed)
      next "—" unless v
      s = sprintf("%.2f", v)
      v == best ? "**#{s}**" : s
    end
    f.puts "| #{bench} | #{cells.join(' | ')} |"
  end
end
puts "wrote #{md_path}"
