// This file is autogenerated from node.def.

typedef node_hash_t (*node_hash_func_t)(struct Node *n);
typedef void (*node_specializer_func_t)(FILE *fp, struct Node *n, bool is_public);
typedef void (*node_dumper_func_t)(FILE *fp, struct Node *n, bool oneline);
typedef void (*node_replacer_func_t)(struct Node *parent, struct Node *old_child, struct Node *new_child);


struct NodeKind {
    const char *default_dispatcher_name;
    node_dispatcher_func_t default_dispatcher;
    node_hash_func_t hash_func;
    node_specializer_func_t specializer;
    node_dumper_func_t dumper;
    node_replacer_func_t replacer;
};

struct node_num_struct {
    int32_t num;
};

struct node_add_struct {
    NODE * lv;
    NODE * rv;
};

struct node_sub_struct {
    NODE * lv;
    NODE * rv;
};

struct node_mul_struct {
    NODE * lv;
    NODE * rv;
};

struct node_div_struct {
    NODE * lv;
    NODE * rv;
};

struct node_mod_struct {
    NODE * lv;
    NODE * rv;
};

struct Node {
    struct NodeHead head;

    union {
        struct node_num_struct node_num;
        struct node_add_struct node_add;
        struct node_sub_struct node_sub;
        struct node_mul_struct node_mul;
        struct node_div_struct node_div;
        struct node_mod_struct node_mod;
    }u;
};

// allocators
NODE *ALLOC_node_num(int32_t num);;
NODE *ALLOC_node_add(NODE * lv, NODE * rv);;
NODE *ALLOC_node_sub(NODE * lv, NODE * rv);;
NODE *ALLOC_node_mul(NODE * lv, NODE * rv);;
NODE *ALLOC_node_div(NODE * lv, NODE * rv);;
NODE *ALLOC_node_mod(NODE * lv, NODE * rv);
