// This file is autogenerated from node.def.

struct node_num_struct {
    int32_t num;
};

struct node_add_struct {
    NODE * lv;
    NODE * rv;
};

struct node_mul_struct {
    NODE * lv;
    NODE * rv;
};

struct Node {
    struct NodeHead head;

    union {
        struct node_num_struct node_num;
        struct node_add_struct node_add;
        struct node_mul_struct node_mul;
    }u;
};

// allocators
NODE *ALLOC_node_num(int32_t num);;
NODE *ALLOC_node_add(NODE * lv, NODE * rv);;
NODE *ALLOC_node_mul(NODE * lv, NODE * rv);
