#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "node.h"
#include "context.h"

// ---------------------------------------------------------------------------
// Hash helpers used by generated node_hash.c.
// ---------------------------------------------------------------------------

static node_hash_t
hash_merge(node_hash_t h, node_hash_t v)
{
    h ^= v + 0x9e3779b97f4a7c15ULL + (h << 12) + (h >> 4);
    return h;
}

static node_hash_t
hash_cstr(const char *s)
{
    node_hash_t h = 14695981039346656037ULL;
    const node_hash_t FNV_PRIME = 1099511628211ULL;
    while (*s) {
        h ^= (unsigned char)(*s++);
        h *= FNV_PRIME;
    }
    return h;
}

static node_hash_t
hash_uint32(uint32_t ui)
{
    node_hash_t x = ui;
    x ^= x >> 33;
    x *= 0xff51afd7ed558ccdULL;
    x ^= x >> 33;
    x *= 0xc4ceb9fe1a85ec53ULL;
    x ^= x >> 33;
    return x;
}

static node_hash_t
hash_uint64(uint64_t u)
{
    node_hash_t x = u;
    x ^= x >> 33;
    x *= 0xff51afd7ed558ccdULL;
    x ^= x >> 33;
    x *= 0xc4ceb9fe1a85ec53ULL;
    x ^= x >> 33;
    return x;
}

__attribute__((unused))
static node_hash_t
hash_double(double d)
{
    union { double d; uint64_t u; } pun;
    pun.d = d;
    return hash_uint64(pun.u);
}

static node_hash_t hash_node(NODE *n);

static node_hash_t
hash_node_inner(NODE *n)
{
    if (!n) return 0;
    if (n->head.flags.has_hash_value) return n->head.hash_value;
    return HASH(n);
}

static node_hash_t
hash_node(NODE *n)
{
    return hash_node_inner(n);
}

// ---------------------------------------------------------------------------
// Allocation, dispatch tracing, name allocation.
// ---------------------------------------------------------------------------

static __attribute__((noinline)) NODE *
node_allocate(size_t size)
{
    NODE *n = (NODE *)calloc(1, size);
    if (!n) {
        fprintf(stderr, "pascalast: out of memory\n");
        exit(1);
    }
    return n;
}

int g_alloc_line;
int pascal_runtime_line;

static void
dispatch_info(CTX *c, NODE *n, bool end)
{
    (void)c; (void)end;
    // Tracking the last entered node lets pascal_error print the
    // source line.  The cost is one int store per dispatch; cheap
    // enough not to matter outside the very tightest loops, and
    // turning it off would lose the diagnostic.
    if (!end) pascal_runtime_line = n->head.line;
}

static const char *
alloc_dispatcher_name(NODE *n)
{
    char buf[64];
    snprintf(buf, sizeof(buf), "SD_%lx", (unsigned long)hash_node(n));
    char *s = malloc(strlen(buf) + 1);
    strcpy(s, buf);
    return s;
}

// ---------------------------------------------------------------------------
// Specialized-code repository (naruby-style AOT).  A flat array of
// {hash, dispatcher_name, dispatcher_fn}; lookup is linear (small N).
// Populated at INIT() from a static `sc_entries[]` table that
// node_specialized.c (auto-generated by `-c`) defines.
// ---------------------------------------------------------------------------

struct specialized_code {
    node_hash_t hash;
    const char *dispatcher_name;
    node_dispatcher_func_t dispatcher;
};

static struct specialized_code_repo {
    uint32_t size;
    uint32_t capa;
    struct specialized_code *entries;
} sc_repo;

static struct specialized_code *
sc_repo_search(node_hash_t h)
{
    for (uint32_t i = 0; i < sc_repo.size; i++) {
        if (sc_repo.entries[i].hash == h) return &sc_repo.entries[i];
    }
    return NULL;
}

static struct specialized_code *
sc_repo_new_entry(void)
{
    if (sc_repo.size < sc_repo.capa) return &sc_repo.entries[sc_repo.size++];
    uint32_t cap = sc_repo.capa ? sc_repo.capa * 2 : 16;
    sc_repo.entries = realloc(sc_repo.entries, sizeof(*sc_repo.entries) * cap);
    if (!sc_repo.entries) {
        fprintf(stderr, "sc_repo: out of memory\n");
        exit(1);
    }
    sc_repo.capa = cap;
    return sc_repo_new_entry();
}

static void
sc_repo_add(NODE *n, node_hash_t h)
{
    struct specialized_code *sc = sc_repo_new_entry();
    sc->hash            = h;
    sc->dispatcher_name = n->head.dispatcher_name;
    sc->dispatcher      = n->head.dispatcher;
}

void sc_repo_clear(void) { sc_repo.size = 0; }
uint32_t sc_repo_count(void) { return sc_repo.size; }
void sc_repo_get(uint32_t i, node_hash_t *h_out, const char **name_out)
{
    if (h_out)    *h_out = sc_repo.entries[i].hash;
    if (name_out) *name_out = sc_repo.entries[i].dispatcher_name;
}

// ---------------------------------------------------------------------------
// Core API: HASH, EVAL, DUMP, OPTIMIZE, SPECIALIZE, code_repo_add.
// ---------------------------------------------------------------------------

node_hash_t
HASH(NODE *n)
{
    if (!n) return 0;
    if (n->head.flags.has_hash_value) return n->head.hash_value;
    if (n->head.kind->hash_func) {
        n->head.flags.has_hash_value = true;
        return n->head.hash_value = (*n->head.kind->hash_func)(n);
    }
    return 0;
}

VALUE
EVAL(CTX *c, NODE *n)
{
    return (*n->head.dispatcher)(c, n);
}

void
DUMP(FILE *fp, NODE *n, bool oneline)
{
    if (!n) {
        fprintf(fp, "<NULL>");
    } else if (n->head.flags.is_dumping) {
        fprintf(fp, "...");
    } else {
        n->head.flags.is_dumping = true;
        (*n->head.kind->dumper)(fp, n, oneline);
        n->head.flags.is_dumping = false;
    }
}

// On every fresh ALLOC the framework calls OPTIMIZE.  If the node's
// structural hash matches an entry in sc_repo, swap the dispatcher to
// the AOT-compiled specialization.
static void
fill_with_sc(NODE *n, struct specialized_code *sc)
{
    n->head.dispatcher_name        = sc->dispatcher_name;
    n->head.dispatcher             = sc->dispatcher;
    n->head.flags.is_specialized   = true;
}

NODE *
OPTIMIZE(NODE *n)
{
    n->head.line = g_alloc_line;
    if (OPTION.no_compiled_code) return n;
    node_hash_t h = hash_node(n);
    struct specialized_code *sc = sc_repo_search(h);
    if (sc) fill_with_sc(n, sc);
    return n;
}

// Recursively emit specialized source for `n` and its sub-trees.  Used
// by SPECIALIZED_SRC to dump a single AST as a self-contained C
// translation unit.
void
SPECIALIZE(FILE *fp, NODE *n)
{
    if (!n || !n->head.kind->specializer) return;
    node_hash_t h = HASH(n);
    if (sc_repo_search(h)) {
        if (!n->head.flags.is_specialized) fill_with_sc(n, sc_repo_search(h));
        return;
    }
    // Eagerly stamp dispatcher_name BEFORE recursing into children.
    // The generated specializer also sets it (post-recursion) — same
    // value, no conflict — but the eager set means a child that
    // cycles back to this node sees the right SD name and can emit a
    // direct call instead of an indirect dispatcher load.  Critical
    // for baked recursive pcalls (fib calling itself): without this
    // the recursive edge falls back to DISPATCH_node_<kind>.
    if (n->head.flags.is_specializing) {
        // Cycle: also flip no_inline so DISPATCHER_NAME emits the
        // runtime dispatcher load form, in case the cycle came in
        // before the eager set somehow runs (defensive — shouldn't
        // happen with the eager set above, but matches the
        // astro_code_store.c contract).
        n->head.flags.no_inline = true;
        return;
    }
    n->head.dispatcher_name = alloc_dispatcher_name(n);
    n->head.flags.is_specializing = true;
    (*n->head.kind->specializer)(fp, n, false);
    n->head.flags.is_specializing = false;
    sc_repo_add(n, h);
}

// Top-level entry: dump specialized source for one AST.  Returns a
// malloc'd string the caller appends to node_specialized.c.
char *
SPECIALIZED_SRC(NODE *n)
{
    if (!n) return NULL;
    char *buf = NULL;
    size_t len = 0;
    FILE *fp = open_memstream(&buf, &len);
    if (!fp) return NULL;
    // Proc-body roots and the main body are emitted as `static inline`
    // (is_public=false) so baked pcall forward-decls — which reference
    // them as static inline — link cleanly.  sc_entries[] takes their
    // address, which forces gcc to emit an out-of-line callable copy
    // in this TU; that satisfies the function-pointer load while still
    // allowing the compiler to inline the SD into call sites where
    // possible.  Eagerly stamp dispatcher_name first (same as
    // SPECIALIZE) so a recursive call inside the body sees the proc's
    // SD name and the AOT'd recursive edge becomes a direct call.
    n->head.dispatcher_name = alloc_dispatcher_name(n);
    n->head.flags.is_specializing = true;
    (*n->head.kind->specializer)(fp, n, false);
    n->head.flags.is_specializing = false;
    fclose(fp);
    return buf;
}

void
code_repo_add(const char *name, NODE *body, bool force)
{
    (void)name; (void)body; (void)force;
}

// astro_fprintf_cstr / astro_fprint_cstr aren't used because we never run
// the SPECIALIZE pass — but the generated dumper/specializer reference
// them, so provide stubs that satisfy the linker if any path slips
// through.
__attribute__((unused)) static void
astro_fprintf_cstr(FILE *fp, const char *s)
{
    if (!s) { fputs("\"\"", fp); return; }
    fputc('"', fp);
    for (const unsigned char *p = (const unsigned char *)s; *p; p++) {
        switch (*p) {
        case '\\': fputs("\\\\", fp); break;
        case '"':  fputs("\\\"", fp); break;
        case '\n': fputs("\\n", fp); break;
        case '\r': fputs("\\r", fp); break;
        case '\t': fputs("\\t", fp); break;
        default:
            if (*p < 0x20 || *p == 0x7f) fprintf(fp, "\\x%02x", *p);
            else fputc(*p, fp);
        }
    }
    fputc('"', fp);
}

__attribute__((unused)) static void
astro_fprint_cstr(FILE *fp, const char *s)
{
    fputc('"', fp);
    for (; *s; s++) {
        switch (*s) {
        case '"':  fputs("\\\"", fp); break;
        case '\\': fputs("\\\\", fp); break;
        case '\n': fputs("\\n", fp); break;
        case '\r': fputs("\\r", fp); break;
        case '\t': fputs("\\t", fp); break;
        default:   fputc(*s, fp);
        }
    }
    fputc('"', fp);
}

// ---------------------------------------------------------------------------
// Generated code.
// ---------------------------------------------------------------------------

#include "node_eval.c"
#include "node_dispatch.c"
#include "node_dump.c"
#include "node_hash.c"
#include "node_specialize.c"
#include "node_replace.c"
#include "node_alloc.c"

#include "node_specialized.c"

#ifndef NODE_SPECIALIZED_INCLUDED
// Empty initial table.  Populated by `pascalast -c FILE.pas`.
static struct specialized_code sc_entries[] = {{0}};
#define SC_ENTRIES_COUNT 0
#endif

void
INIT(void)
{
    GC_init();

    sc_repo.size = SC_ENTRIES_COUNT;
    sc_repo.capa = (sc_repo.size == 0) ? 16 : sc_repo.size * 2;
    sc_repo.entries = malloc(sc_repo.capa * sizeof(struct specialized_code));
    if (sc_repo.size > 0) {
        memcpy(sc_repo.entries, sc_entries, sc_repo.size * sizeof(struct specialized_code));
    }
}
