require 'astrogen'

# Per-language ASTroGen extension for pascalast.  Tells the default
# generators how to deal with:
#  - `@ref` cache operands (struct types the framework can't introspect)
#  - `@nohash` operands (NODE * baked-call body — must not contribute to
#    HASH(parent) because that would create a cycle parent → body →
#    pcall_to_self_in_body → parent, and must not auto-recurse during
#    SPECIALIZE because the body's SD is generated independently in
#    write_specialized).  We still emit body's dispatcher_name as an
#    argument so the AOT-emitted SD calls it directly.
# See ascheme_gen.rb for the @ref-only pattern.
class PascalastNodeDef < ASTroGen::NodeDef
  class Node < ASTroGen::NodeDef::Node
    # Accept @nohash alongside @ref; the base regex hardcodes @ref only.
    def parse_operands(str)
      @operands = str.split(',').tap do
        @prefix_args = it.shift(common_param_count)
      end.map do
        case it.strip
        when /(.+)\s+([a-zA-Z_][a-zA-Z0-9_]*(?:@(?:ref|nohash))?)$/
          self.class::Operand.new $1, $2
        when /(.+\*)([a-zA-Z_][a-zA-Z0-9_]*(?:@(?:ref|nohash))?)$/
          self.class::Operand.new $1, $2
        else
          raise "ill-formed field: #{it}"
        end
      end
    end

    class Operand < ASTroGen::NodeDef::Node::Operand
      def initialize(type, name)
        @nohash = name.end_with?('@nohash')
        name = name.sub(/@nohash$/, '') if @nohash
        super
      end

      def nohash? = @nohash

      def hash_call(val, kind: :horg)
        return "0" if ref? || nohash?
        super
      end

      def build_dumper(name)
        return nil if ref?
        super
      end

      def build_specializer(name)
        if ref?
          arg = "    fprintf(fp, \"        &n->u.#{name}.#{self.name}\");"
          return nil, arg
        end
        if nohash? && @type == 'NODE *'
          # Skip auto-recurse (cn = nil): body's SD is generated by
          # write_specialized's outer loop.  Emit dispatcher_name so the
          # parent SD calls body's SD directly.  If body is NULL (pcall
          # to an unresolvable proc — defensive only), emit literal
          # NULL,NULL so the EVAL's UNLIKELY(!body) fallback kicks in.
          arg = "    if (n->u.#{name}.#{self.name}) {\n" +
                "        fprintf(fp, \"        n->u.#{name}.#{self.name},\\n\");\n" +
                "        fprintf(fp, \"        %s\", DISPATCHER_NAME(n->u.#{name}.#{self.name}));\n" +
                "    } else {\n" +
                "        fprintf(fp, \"        NULL,\\n\");\n" +
                "        fprintf(fp, \"        NULL\");\n" +
                "    }"
          return nil, arg
        end
        super
      end
    end
  end
end
