#ifndef NODE_H
#define NODE_H 1

// String/stdlib funcs are referenced from the generated node_eval.c
// (find_func_entry uses strcmp, call_check uses exit).  gcc tolerates
// the implicit decls; clang does not.  Pull them in here so every
// AOT/PG SD .c that includes node_eval.c sees the right prototypes.
#include <stdlib.h>
#include <string.h>

#include "context.h"
// gc.h defines aro_gc_wb (write barrier) used by EVAL_node_call_aset
// inside node_eval.c.  Non-gen backends provide it as a `static inline`
// stub; gen backends export it as an extern.  Either way, SD .c that
// includes node_eval.c needs the declaration / inline-body in scope —
// otherwise gcc emits a call to the implicit `extern aro_gc_wb` and
// dlopen of all.so fails with an undefined symbol on non-WB GC backends
// (e.g. GC=copy) for any program that touches array write (a[i] = v).
#include "gc.h"
// node_def's EVAL body calls astro_cs_load(body, name) for PGC dispatch
// loading; the SD .c files include node_eval.c so they need the
// declaration too.  We include only the prototype (not the full
// astro_code_store.h) because SD .c compiles don't have -I runtime/.
struct Node;
bool astro_cs_load(struct Node *n, const char *file);

typedef struct Node NODE;
// 4-arg dispatcher: (c, n, fp, sp).  fp is the function frame base
// (locals at fp[0..locals_cnt-1]).  sp is the current scratch top — each
// NODE_DEF that needs roots writes intermediates to sp[0], sp[1], ... and
// passes `sp + N` to children so the children's scratch sits above ours.
// baruby_precise: precise mark&sweep scans c->env..c->sp to find roots.
typedef RESULT (*node_dispatcher_func_t)(CTX *c, NODE *n, VALUE *fp, VALUE *sp);
typedef uint64_t node_hash_t;

void INIT(void);
node_hash_t HASH(NODE *n);
void DUMP(FILE *fp, NODE *n, bool oneline);
NODE *OPTIMIZE(NODE *n);
void SPECIALIZE(FILE *fp, NODE *n);
char *SPECIALIZED_SRC(NODE *n);

void clear_hash(NODE *n);

NODE *code_repo_find(node_hash_t h);
NODE *code_repo_find_by_name(const char *name);
void code_repo_add(const char *name, NODE *body, bool force_add);
void code_repo_add2(const char *name, NODE *body, bool force_add, uint32_t locals_cnt);
uint32_t code_repo_find_locals_cnt_by_body(NODE *body);
uint32_t code_repo_find_locals_cnt_by_name(const char *name);

// Enable optional NodeHead fields used by baruby
#define ASTRO_NODEHEAD_PARENT
#define ASTRO_NODEHEAD_JIT_STATUS
#define ASTRO_NODEHEAD_DISPATCH_CNT

struct NodeHead {
    struct NodeFlags {
        bool has_hash_value;
        bool has_hash_opt;       // tracked by code_store for PGC; v0 unused
        bool is_specialized;
        bool is_specializing; // to prohibit recursive specializing
        bool is_dumping;      // to prohibit recursive dumping
        bool no_inline;
    } flags;

    const struct NodeKind *kind;
    struct Node *parent;

    node_hash_t hash_value;
    node_hash_t hash_opt;        // same as hash_value when PGC inactive

    const char *dispatcher_name;

    // use in exec
    node_dispatcher_func_t dispatcher;

    enum jit_status {
        JIT_STATUS_Unknown,
        JIT_STATUS_Querying,
        JIT_STATUS_NotFound,
        JIT_STATUS_Compiling,
        JIT_STATUS_Compiled,
    } jit_status;

    unsigned int dispatch_cnt;
    int line;                    // source line for diagnostics; v0 unused
};

#define DISPATCHER_NAME(n) (n->head.flags.no_inline) ? (#n "->head.dispatcher") : (n->head.dispatcher_name)

// HORG / HOPT split.  HORG is the structural hash (= HASH() generated by
// the framework); baruby keeps sp_body excluded from HORG so the call
// site's identity is stable across runtime sp_body mutations.  HOPT
// folds the speculated sp_body's structure in via hash_node_opt, so a
// pg_call against different profile bodies bakes as a distinct PGSD_<HOPT>.
#define HORG(n) HASH(n)
node_hash_t HOPT(NODE *n);
node_hash_t hash_node_opt(NODE *n);

#include "node_head.h"
#include "bf.h"

static inline RESULT
EVAL(CTX *c, NODE *n, VALUE *fp, VALUE *sp)
{
    return (*n->head.dispatcher)(c, n, fp, sp);
}

// Custom EVAL_ARG that advances sp for the child.  In NODE_DEF BODY
// scope, fp and sp are parameters of the enclosing EVAL_<name>.
// `n_node##_dispatcher` is the per-operand dispatcher pointer the
// framework adds to the EVAL_<name> signature.
//
// Use this whenever the parent NODE_DEF holds a VALUE root in sp[]:
//   sp[0] = UNWRAP(BARUBY_EVAL_ARG(c, lv, sp + 1));
// to ensure the child writes its own scratch above the parent's slots.
// For pass-through (no root spill in parent), the framework's plain
// EVAL_ARG(c, lv) reuses the parent's sp unchanged — equivalent to
// BARUBY_EVAL_ARG(c, lv, sp).
#define BARUBY_EVAL_ARG(c, n_node, new_sp) ((*n_node##_dispatcher)(c, n_node, fp, new_sp))

// Per-variant slowpaths.  Updated to 4-arg sig for sp threading.
RESULT node_call_slowpath        (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_call_0_slowpath      (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_call_1_slowpath      (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_call_2_slowpath      (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_call_3_slowpath      (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_call2_slowpath       (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_pg_call0_slowpath    (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_pg_call1_slowpath    (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_pg_call2_slowpath    (CTX *c, NODE *n, VALUE *fp, VALUE *sp);
RESULT node_pg_call3_slowpath    (CTX *c, NODE *n, VALUE *fp, VALUE *sp);

#endif // NODE_H
